/**
 * WaveTap token compiler — zero-dependency.
 *
 * Reads the DTCG source in ../../design-tokens/ and emits the consumable
 * artifacts in src/:
 *   - tokens.gen.ts  — typed JS objects (colors, spacing, radius, shadows, …)
 *   - theme.css      — HeroUI v3 theme-variable overrides (light mode)
 *
 * Run: `pnpm --filter @wavetap/tokens build` (or `node build.mjs`).
 * Edit the DTCG JSON, never the generated files.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const tokensDir = resolve(here, "../../design-tokens");
const srcDir = resolve(here, "src");

const primitives = JSON.parse(readFileSync(resolve(tokensDir, "primitives.json"), "utf8"));
const semantic = JSON.parse(readFileSync(resolve(tokensDir, "semantic.json"), "utf8"));

const isMeta = (k) => k.startsWith("$");

/** Walk a DTCG group → plain { key: value } object (one level of leaves). */
function leaves(group) {
  const out = {};
  for (const [k, v] of Object.entries(group)) {
    if (isMeta(k)) continue;
    if (v && typeof v === "object" && "$value" in v) out[k] = v.$value;
    else if (v && typeof v === "object") out[k] = leaves(v); // nested group (e.g. color.neutral)
  }
  return out;
}

/** Flat lookup of every primitive leaf: "color.accent.500" -> "#E8694A". */
function flatten(group, prefix, acc) {
  for (const [k, v] of Object.entries(group)) {
    if (isMeta(k)) continue;
    const path = prefix ? `${prefix}.${k}` : k;
    if (v && typeof v === "object" && "$value" in v) acc[path] = v.$value;
    else if (v && typeof v === "object") flatten(v, path, acc);
  }
  return acc;
}

const lookup = flatten(primitives, "", {});

/** Resolve a DTCG alias like "{color.accent.500}" to its primitive value. */
function resolveAlias(value) {
  if (typeof value !== "string") return value;
  const m = value.match(/^\{(.+)\}$/);
  if (!m) return value;
  const v = lookup[m[1]];
  if (v === undefined) throw new Error(`Unresolved token alias: ${value}`);
  return v;
}

// ---- tokens.gen.ts -------------------------------------------------------
const colors = leaves(primitives.color);
const spacing = leaves(primitives.space);
const radius = leaves(primitives.radius);
const shadows = leaves(primitives.shadow);
const fontFamily = leaves(primitives.fontFamily);
const fontSizes = leaves(primitives.fontSize);
const fontWeights = leaves(primitives.fontWeight);
const lineHeights = leaves(primitives.lineHeight);

const lit = (o) => JSON.stringify(o, null, 2).replace(/"([\w-]+)":/g, "$1:");

const ts = `// AUTO-GENERATED by packages/tokens/build.mjs from design-tokens/*.json.
// Do not edit by hand — edit the DTCG source and re-run the build.
/* eslint-disable */

export const colors = ${lit(colors)} as const;

export const spacing = ${lit(spacing)} as const;

export const radius = ${lit(radius)} as const;

export const shadows = ${lit(shadows)} as const;

export const fontFamily = ${lit(fontFamily)} as const;

export const fontSizes = ${lit(fontSizes)} as const;

export const fontWeights = ${lit(fontWeights)} as const;

export const lineHeights = ${lit(lineHeights)} as const;

export const tokens = {
  colors,
  spacing,
  radius,
  shadows,
  fontFamily,
  fontSizes,
  fontWeights,
  lineHeights,
} as const;

export type Tokens = typeof tokens;
`;

writeFileSync(resolve(srcDir, "tokens.gen.ts"), ts);

// ---- theme.css -----------------------------------------------------------
const heroVars = Object.entries(semantic.heroui)
  .filter(([k]) => !isMeta(k))
  .map(([name, def]) => `  --${name}: ${resolveAlias(def.$value)};`)
  .join("\n");

// HeroUI base radius is in rem; convert the px alias.
const radiusPx = parseFloat(resolveAlias(semantic.radius.base.$value));
const radiusRem = `${radiusPx / 16}rem`;

const css = `/* AUTO-GENERATED by packages/tokens/build.mjs from design-tokens/*.json.
 * Do not edit by hand — edit the DTCG source and re-run the build.
 *
 * WaveTap brand applied to HeroUI v3 theme variables (light mode). Import AFTER
 * the HeroUI CSS layers so these overrides win:
 *   @import "tailwindcss";
 *   @import "@heroui/styles";
 *   @import "@heroui-pro/react/css";
 *   @import "@wavetap/tokens/theme.css";
 * HeroUI auto-derives *-hover and *-soft variants from these via color-mix.
 */
:root {
  color-scheme: light;

  /* Brand → HeroUI semantic roles */
${heroVars}

  /* Radius base (HeroUI derives --field-radius = --radius * 1.5) */
  --radius: ${radiusRem};

  /* Type */
  --font-sans: ${fontFamily.sans};
}

body {
  background-color: var(--background);
  color: var(--foreground);
  font-family: var(--font-sans);
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
}
`;

writeFileSync(resolve(srcDir, "theme.css"), css);

// ---- native-theme.css (HeroUI Native / Uniwind) -------------------------
// HeroUI Native uses the same semantic variable names as web HeroUI, but they
// live in Uniwind's `@layer theme` / `@variant light` block and prefer oklch
// (an open Uniwind issue makes color-mix on hex resolve "invalid" on native,
// breaking Reanimated colour animations). So we emit the identical brand
// mapping converted to oklch. Light only for launch — dark inherits HeroUI's
// default theme until we author a `@variant dark` block.
function hexToOklch(hex) {
  const h = hex.replace("#", "");
  const to = (i) => parseInt(h.slice(i, i + 2), 16) / 255;
  const lin = (c) => (c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4);
  const r = lin(to(0)), g = lin(to(2)), b = lin(to(4));
  const l = 0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b;
  const m = 0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b;
  const s = 0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b;
  const l_ = Math.cbrt(l), m_ = Math.cbrt(m), s_ = Math.cbrt(s);
  const L = 0.2104542553 * l_ + 0.793617785 * m_ - 0.0040720468 * s_;
  const aa = 1.9779984951 * l_ - 2.428592205 * m_ + 0.4505937099 * s_;
  const bb = 0.0259040371 * l_ + 0.7827717662 * m_ - 0.808675766 * s_;
  const C = Math.sqrt(aa * aa + bb * bb);
  let H = (Math.atan2(bb, aa) * 180) / Math.PI;
  if (H < 0) H += 360;
  const round = (n, d) => Number(n.toFixed(d));
  return C < 1e-4
    ? `oklch(${round(L, 4)} 0 0)`
    : `oklch(${round(L, 4)} ${round(C, 4)} ${round(H, 2)})`;
}

const nativeVars = Object.entries(semantic.heroui)
  .filter(([k]) => !isMeta(k))
  .map(([name, def]) => `      --${name}: ${hexToOklch(resolveAlias(def.$value))};`)
  .join("\n");
const nativeBlock = `${nativeVars}\n      --radius: ${radiusRem};`;

const nativeCss = `/* AUTO-GENERATED by packages/tokens/build.mjs from design-tokens/*.json.
 * Do not edit by hand — edit the DTCG source and re-run the build.
 *
 * WaveTap brand applied to HeroUI Native (Uniwind) theme variables in oklch.
 * Import in apps/mobile/global.css AFTER the heroui-native styles:
 *   @import "tailwindcss";
 *   @import "uniwind";
 *   @import "heroui-native/styles";
 *   @import "@wavetap/tokens/native-theme.css";
 *
 * Uniwind requires every theme variant to declare the same variable set, so we
 * emit light AND dark. 09_DESIGN_SYSTEM is light-first with no dark palette yet
 * and the app is pinned to light (app.json userInterfaceStyle), so dark mirrors
 * the light brand for now — replace with a real dark palette when it's designed.
 */
@layer theme {
  @variant light {
${nativeBlock}
  }
  @variant dark {
${nativeBlock}
  }
}
`;

writeFileSync(resolve(srcDir, "native-theme.css"), nativeCss);

console.log("✓ tokens.gen.ts + theme.css + native-theme.css generated from design-tokens/");
