/**
 * WaveTap token compiler — zero-dependency.
 *
 * Reads the DTCG source in ../../design-tokens/ and emits the consumable
 * artifacts in src/:
 *   - tokens.gen.ts  — typed JS objects (colors, spacing, radius, shadows, …)
 *   - theme.css      — HeroUI v3 theme-variable overrides (light mode)
 *
 * Run: `pnpm --filter @wavetap/tokens build` (or `node build.mjs`).
 * Edit the DTCG JSON, never the generated files.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const tokensDir = resolve(here, "../../design-tokens");
const srcDir = resolve(here, "src");

const primitives = JSON.parse(readFileSync(resolve(tokensDir, "primitives.json"), "utf8"));
const semantic = JSON.parse(readFileSync(resolve(tokensDir, "semantic.json"), "utf8"));

const isMeta = (k) => k.startsWith("$");

/** Walk a DTCG group → plain { key: value } object (one level of leaves). */
function leaves(group) {
  const out = {};
  for (const [k, v] of Object.entries(group)) {
    if (isMeta(k)) continue;
    if (v && typeof v === "object" && "$value" in v) out[k] = v.$value;
    else if (v && typeof v === "object") out[k] = leaves(v); // nested group (e.g. color.neutral)
  }
  return out;
}

/** Flat lookup of every primitive leaf: "color.accent.500" -> "#E8694A". */
function flatten(group, prefix, acc) {
  for (const [k, v] of Object.entries(group)) {
    if (isMeta(k)) continue;
    const path = prefix ? `${prefix}.${k}` : k;
    if (v && typeof v === "object" && "$value" in v) acc[path] = v.$value;
    else if (v && typeof v === "object") flatten(v, path, acc);
  }
  return acc;
}

const lookup = flatten(primitives, "", {});

/** Resolve a DTCG alias like "{color.accent.500}" to its primitive value. */
function resolveAlias(value) {
  if (typeof value !== "string") return value;
  const m = value.match(/^\{(.+)\}$/);
  if (!m) return value;
  const v = lookup[m[1]];
  if (v === undefined) throw new Error(`Unresolved token alias: ${value}`);
  return v;
}

// ---- tokens.gen.ts -------------------------------------------------------
const colors = leaves(primitives.color);
const spacing = leaves(primitives.space);
const radius = leaves(primitives.radius);
const shadows = leaves(primitives.shadow);
const fontFamily = leaves(primitives.fontFamily);
const fontSizes = leaves(primitives.fontSize);
const fontWeights = leaves(primitives.fontWeight);
const lineHeights = leaves(primitives.lineHeight);

const lit = (o) => JSON.stringify(o, null, 2).replace(/"([\w-]+)":/g, "$1:");

const ts = `// AUTO-GENERATED by packages/tokens/build.mjs from design-tokens/*.json.
// Do not edit by hand — edit the DTCG source and re-run the build.
/* eslint-disable */

export const colors = ${lit(colors)} as const;

export const spacing = ${lit(spacing)} as const;

export const radius = ${lit(radius)} as const;

export const shadows = ${lit(shadows)} as const;

export const fontFamily = ${lit(fontFamily)} as const;

export const fontSizes = ${lit(fontSizes)} as const;

export const fontWeights = ${lit(fontWeights)} as const;

export const lineHeights = ${lit(lineHeights)} as const;

export const tokens = {
  colors,
  spacing,
  radius,
  shadows,
  fontFamily,
  fontSizes,
  fontWeights,
  lineHeights,
} as const;

export type Tokens = typeof tokens;
`;

writeFileSync(resolve(srcDir, "tokens.gen.ts"), ts);

// ---- theme.css -----------------------------------------------------------
const heroVars = Object.entries(semantic.heroui)
  .filter(([k]) => !isMeta(k))
  .map(([name, def]) => `  --${name}: ${resolveAlias(def.$value)};`)
  .join("\n");

// HeroUI base radius is in rem; convert the px alias.
const radiusPx = parseFloat(resolveAlias(semantic.radius.base.$value));
const radiusRem = `${radiusPx / 16}rem`;

const css = `/* AUTO-GENERATED by packages/tokens/build.mjs from design-tokens/*.json.
 * Do not edit by hand — edit the DTCG source and re-run the build.
 *
 * WaveTap brand applied to HeroUI v3 theme variables (light mode). Import AFTER
 * the HeroUI CSS layers so these overrides win:
 *   @import "tailwindcss";
 *   @import "@heroui/styles";
 *   @import "@heroui-pro/react/css";
 *   @import "@wavetap/tokens/theme.css";
 * HeroUI auto-derives *-hover and *-soft variants from these via color-mix.
 */
:root {
  color-scheme: light;

  /* Brand → HeroUI semantic roles */
${heroVars}

  /* Radius base (HeroUI derives --field-radius = --radius * 1.5) */
  --radius: ${radiusRem};

  /* Type */
  --font-sans: ${fontFamily.sans};
}

body {
  background-color: var(--background);
  color: var(--foreground);
  font-family: var(--font-sans);
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
}
`;

writeFileSync(resolve(srcDir, "theme.css"), css);

console.log("✓ tokens.gen.ts + theme.css generated from design-tokens/");
